version: '3.7'
services:
  prometheus:
    restart: always
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
  grafana:
    restart: always
    image: grafana/grafana:latest
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_AUTH_PROXY_AUTO_SIGN_UP=false
      - GF_AUTH_PROXY_ENABLED=true

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./www:/www
